In [26]:
# Loding Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import nltk

In [27]:
# Load some sample data

# define documents  -> In place of Below data we can take any data:

docs = ['kamal Well done!',
'Good work',
'Great effort',
'nice work',
'Excellent!',
'Weak',
'Poor effort!',
'not good',
'poor work',
'Could have done better.']
# define class labels
labels = [1,1,1,1,1,0,0,0,0,0]

In [28]:
training_ind_data = docs[:7]
val_ind_data = docs[7:9]
test_ind_data = docs[9:]


training_dep_data = labels[:7]
val_dep_data = labels[7:9]
test_dep_data = labels[9:]

In [29]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [30]:
# we need to give to simple RNN:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation,BatchNormalization,Flatten,Embedding,SimpleRNN,Masking,Bidirectional
from tensorflow.keras.activations import sigmoid,relu,leaky_relu,softmax
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [31]:
dic_size = 1000 # each word one unique value

train_ind_values = [one_hot(i,dic_size) for i in  training_ind_data]
val_ind_values = [one_hot(i,dic_size) for i in  val_ind_data]

In [32]:
train_ind_values

[[760, 336, 707], [871, 983], [842, 552], [169, 983], [106], [863], [594, 552]]

In [33]:
val_ind_values

[[100, 871], [594, 983]]

In [34]:
train_inputs = pad_sequences(train_ind_values,maxlen=500,padding='post')
train_inputs

array([[760, 336, 707, ...,   0,   0,   0],
       [871, 983,   0, ...,   0,   0,   0],
       [842, 552,   0, ...,   0,   0,   0],
       ...,
       [106,   0,   0, ...,   0,   0,   0],
       [863,   0,   0, ...,   0,   0,   0],
       [594, 552,   0, ...,   0,   0,   0]], dtype=int32)

In [35]:
val_inputs = pad_sequences(val_ind_values,maxlen=500,padding='post')
val_inputs

array([[100, 871,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [36]:
train_inputs

array([[760, 336, 707, ...,   0,   0,   0],
       [871, 983,   0, ...,   0,   0,   0],
       [842, 552,   0, ...,   0,   0,   0],
       ...,
       [106,   0,   0, ...,   0,   0,   0],
       [863,   0,   0, ...,   0,   0,   0],
       [594, 552,   0, ...,   0,   0,   0]], dtype=int32)

In [37]:
training_dep_data

[1, 1, 1, 1, 1, 0, 0]

In [38]:
val_inputs

array([[100, 871,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [39]:
val_dep_data

[0, 0]

#Give the data to  Simple RNN

#Simple RNN Architecture

In [40]:
import warnings
warnings.filterwarnings('ignore')

model = Sequential()

model.add(Embedding(input_dim=dic_size,output_dim=5,input_length=500)) # means
# user is Telling 1000 unique words in data each word 5 dim and every sentence has 500 words max

model.add(Masking(mask_value=0.0)) # tells model to ignore padded 0.0 values


model.add(Bidirectional(SimpleRNN(units = 3,return_sequences=True,name = 'Hidden_layer_1')))

model.add(Bidirectional(SimpleRNN(units = 4,return_sequences=True,name = 'Hidden_layer_2')))

model.add(Bidirectional(SimpleRNN(units = 5,return_sequences=False,name = 'Hidden_layer_3')))

model.add(Dense(units = 1,activation='sigmoid',name='output_layer'))

In [41]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [42]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ masking_1 (Masking)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [43]:
train_labels = np.array(training_dep_data).reshape(-1,1)
train_labels.shape

(7, 1)

In [44]:
val_labels = np.array(val_dep_data).reshape(-1,1)
val_labels.shape

(2, 1)

In [45]:
train_inputs.shape

(7, 500)

In [46]:
val_inputs.shape

(2, 500)

In [47]:
model.fit(train_inputs, train_labels, epochs=10,
          batch_size=1, verbose=1,
          validation_data=(val_inputs,val_labels))


Epoch 1/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 12s 642ms/step - accuracy: 0.7143 - loss: 0.6513 - val_accuracy: 0.0000e+00 - val_loss: 0.9603
Epoch 2/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 5s 616ms/step - accuracy: 0.7143 - loss: 0.6148 - val_accuracy: 0.0000e+00 - val_loss: 1.0372
Epoch 3/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 4s 511ms/step - accuracy: 0.7143 - loss: 0.5971 - val_accuracy: 0.0000e+00 - val_loss: 1.0665
Epoch 4/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 3s 487ms/step - accuracy: 0.7143 - loss: 0.5832 - val_accuracy: 0.0000e+00 - val_loss: 1.1838
Epoch 5/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 7s 862ms/step - accuracy: 0.7143 - loss: 0.5577 - val_accuracy: 0.0000e+00 - val_loss: 1.2325
Epoch 6/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 8s 489ms/step - accuracy: 0.7143 - loss: 0.5295 - val_accuracy: 0.0000e+00 - val_loss: 1.2647
Epoch 7/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 5s 710ms/step - accuracy: 0.7143 - loss: 0.4808 - val_accuracy: 0.0000e+00 - val_loss: 1.1983
Epoch 8/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 3s 480ms/step - accuracy: 0.7143 - loss: 0.4309 - val

In [48]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (1, 500, 5)            │         5,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ masking_1 (Masking)             │ (1, 500, 5)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (1, 500, 6)            │            54 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (1, 500, 8)            │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (1, 10)                │           140 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ (1, 1)                 │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15,881 (62.04 KB)

 Trainable params: 5,293 (20.68 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 10,588 (41.36 KB)

In [49]:
test_ind_data

['Could have done better.']

**Test Data point**

In [50]:
check = ['Could have done better']
f = one_hot(check[0],dic_size)
print(f)
f1 = pad_sequences([f],maxlen=500,padding='post')
print(f1)
if model.predict(f1)[0][0] > 0.5:
  print(f'Good Label : {1}')
else:
  print(f'Bad Label : {0}')

[356, 699, 707, 784]
[[356 699 707 784   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0