In [1]:
# Loding Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import nltk

In [2]:
# Load some sample data

# define documents  -> In place of Below data we can take any data:

docs = ['kamal Well done!',
'Good work',
'Great effort',
'nice work',
'Excellent!',
'Weak',
'Poor effort!',
'not good',
'poor work',
'Could have done better.']
# define class labels
labels = [1,1,1,1,1,0,0,0,0,0]

In [3]:
training_ind_data = docs[:7]
val_ind_data = docs[7:9]
test_ind_data = docs[9:]


training_dep_data = labels[:7]
val_dep_data = labels[7:9]
test_dep_data = labels[9:]

In [4]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [5]:
# we need to give to simple RNN:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation,BatchNormalization,Flatten,Embedding,SimpleRNN,Masking,Bidirectional
from tensorflow.keras.activations import sigmoid,relu,leaky_relu,softmax
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [6]:
dic_size = 1000 # each word one unique value

train_ind_values = [one_hot(i,dic_size) for i in  training_ind_data]
val_ind_values = [one_hot(i,dic_size) for i in  val_ind_data]

In [7]:
train_ind_values

[[547, 57, 127], [597, 108], [823, 263], [407, 108], [524], [661], [615, 263]]

In [8]:
val_ind_values

[[420, 597], [615, 108]]

In [9]:
train_inputs = pad_sequences(train_ind_values,maxlen=500,padding='post')
train_inputs

array([[547,  57, 127, ...,   0,   0,   0],
       [597, 108,   0, ...,   0,   0,   0],
       [823, 263,   0, ...,   0,   0,   0],
       ...,
       [524,   0,   0, ...,   0,   0,   0],
       [661,   0,   0, ...,   0,   0,   0],
       [615, 263,   0, ...,   0,   0,   0]], dtype=int32)

In [10]:
val_inputs = pad_sequences(val_ind_values,maxlen=500,padding='post')
val_inputs

array([[420, 597,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [11]:
train_inputs

array([[547,  57, 127, ...,   0,   0,   0],
       [597, 108,   0, ...,   0,   0,   0],
       [823, 263,   0, ...,   0,   0,   0],
       ...,
       [524,   0,   0, ...,   0,   0,   0],
       [661,   0,   0, ...,   0,   0,   0],
       [615, 263,   0, ...,   0,   0,   0]], dtype=int32)

In [12]:
training_dep_data

[1, 1, 1, 1, 1, 0, 0]

In [13]:
val_inputs

array([[420, 597,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [14]:
val_dep_data

[0, 0]

#Give the data to  Simple RNN

#Simple RNN Architecture

In [15]:
import warnings
warnings.filterwarnings('ignore')

model = Sequential()

model.add(Embedding(input_dim=dic_size,output_dim=5,input_length=500)) # means
# user is Telling 1000 unique words in data each word 5 dim and every sentence has 500 words max

model.add(Masking(mask_value=0.0)) # tells model to ignore padded 0.0 values


model.add(SimpleRNN(units = 3,return_sequences=True,name = 'Hidden_layer_1'))

model.add(SimpleRNN(units = 4,return_sequences=True,name = 'Hidden_layer_2'))

model.add(SimpleRNN(units = 5,return_sequences=False,name = 'Hidden_layer_3'))

model.add(Dense(units = 1,activation='sigmoid',name='output_layer'))

In [16]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ masking (Masking)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_layer_1 (SimpleRNN)      │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_layer_2 (SimpleRNN)      │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_layer_3 (SimpleRNN)      │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
train_labels = np.array(training_dep_data).reshape(-1,1)
train_labels.shape

(7, 1)

In [19]:
val_labels = np.array(val_dep_data).reshape(-1,1)
val_labels.shape

(2, 1)

In [20]:
train_inputs.shape

(7, 500)

In [21]:
val_inputs.shape

(2, 500)

In [22]:
model.fit(train_inputs, train_labels, epochs=10,
          batch_size=1, verbose=1,
          validation_data=(val_inputs,val_labels))


Epoch 1/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 8s 372ms/step - accuracy: 0.5714 - loss: 0.7409 - val_accuracy: 0.0000e+00 - val_loss: 1.2709
Epoch 2/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 278ms/step - accuracy: 0.7143 - loss: 0.6025 - val_accuracy: 0.0000e+00 - val_loss: 1.2926
Epoch 3/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 277ms/step - accuracy: 0.7143 - loss: 0.5990 - val_accuracy: 0.0000e+00 - val_loss: 1.2856
Epoch 4/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 3s 341ms/step - accuracy: 0.7143 - loss: 0.5989 - val_accuracy: 0.0000e+00 - val_loss: 1.2832
Epoch 5/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 3s 371ms/step - accuracy: 0.7143 - loss: 0.5988 - val_accuracy: 0.0000e+00 - val_loss: 1.2799
Epoch 6/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 278ms/step - accuracy: 0.7143 - loss: 0.5989 - val_accuracy: 0.0000e+00 - val_loss: 1.2791
Epoch 7/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 279ms/step - accuracy: 0.7143 - loss: 0.5992 - val_accuracy: 0.0000e+00 - val_loss: 1.2838
Epoch 8/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 278ms/step - accuracy: 0.7143 - loss: 0.6009 - val_

In [23]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (1, 500, 5)            │         5,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ masking (Masking)               │ (1, 500, 5)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_layer_1 (SimpleRNN)      │ (1, 500, 3)            │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_layer_2 (SimpleRNN)      │ (1, 500, 4)            │            32 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_layer_3 (SimpleRNN)      │ (1, 5)                 │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ (1, 1)                 │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15,347 (59.95 KB)

 Trainable params: 5,115 (19.98 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 10,232 (39.97 KB)

In [24]:
test_ind_data

['Could have done better.']

**Test Data point**

In [25]:
check = ['Could have done better']
f = one_hot(check[0],dic_size)
print(f)
f1 = pad_sequences([f],maxlen=500,padding='post')
print(f1)
if model.predict(f1)[0][0] > 0.5:
  print(f'Good Label : {1}')
else:
  print(f'Bad Label : {0}')

[694, 447, 127, 947]
[[694 447 127 947   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0